In [849]:
import numpy as np
import math
import cv2
from random import shuffle                            #
import matplotlib.pyplot as plt
import skimage.morphology
from Aggregated_Jaccard_Index import Remap_Label

In [850]:
pred1=np.array([[0,1,0,0,1,1,0,1,0,1,0,0],
              [0,1,0,0,1,1,0,1,0,1,0,1],
               [0,1,0,0,1,1,0,1,0,1,0,1],
               [0,1,0,0,1,1,0,1,0,1,0,1],
               [0,1,0,0,1,1,0,1,0,1,0,1]])
label_pred = skimage.morphology.label(pred1)
pred1=Remap_Label(label_pred)

In [851]:
pred1

array([[0, 1, 0, 0, 2, 2, 0, 3, 0, 4, 0, 0],
       [0, 1, 0, 0, 2, 2, 0, 3, 0, 4, 0, 5],
       [0, 1, 0, 0, 2, 2, 0, 3, 0, 4, 0, 5],
       [0, 1, 0, 0, 2, 2, 0, 3, 0, 4, 0, 5],
       [0, 1, 0, 0, 2, 2, 0, 3, 0, 4, 0, 5]], dtype=int32)

In [852]:
val1=np.array([[0,1,0,0,0,0,0,0,0,0,0,0],
         [0,1,0,0,0,1,1,0,0,0,0,1],
              [0,1,0,1,0,1,1,0,0,0,0,1],
              [0,1,0,0,0,1,1,0,0,0,0,1],
              [0,1,0,1,1,0,0,0,0,0,0,1],])

val1 = skimage.morphology.label(val1)
val1=remap_label(val1)
val1=remap_label(val1)

In [853]:
val1

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 0, 3],
       [0, 1, 0, 4, 0, 2, 2, 0, 0, 0, 0, 3],
       [0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 0, 3],
       [0, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 3]], dtype=int32)

In [854]:
true_id_list= list(np.unique(val1))
pred_id_list = list(np.unique(pred1))

true_masks=[None,]
true_masks

[None]

In [855]:
true_id_list

[0, 1, 2, 3, 4]

In [856]:
for t in true_id_list[1:]:
    
    t_mask= np.array(val1==t,np.uint8)
    true_masks.append(t_mask)

In [857]:
true_masks

[None, array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=uint8), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)]

In [858]:
pred_masks = [None,]
for p in pred_id_list[1:]:
   
    p_mask = np.array(pred1 == p, np.uint8)
    pred_masks.append(p_mask)
pred_masks

[None, array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8), array([[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0]], dtype=uint8), array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]], dtype=uint8), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=uint8), array([[0, 0, 0, 

In [859]:
pairwise_inter= np.zeros([len(true_id_list)-1,len(pred_id_list)-1], dtype= np.float64)

In [860]:
pairwise_union = np.zeros([len(true_id_list) -1, 
                               len(pred_id_list) -1], dtype=np.float64)

In [861]:
val1

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 0, 3],
       [0, 1, 0, 4, 0, 2, 2, 0, 0, 0, 0, 3],
       [0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 0, 3],
       [0, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 3]], dtype=int32)

In [862]:
pred1

array([[0, 1, 0, 0, 2, 2, 0, 3, 0, 4, 0, 0],
       [0, 1, 0, 0, 2, 2, 0, 3, 0, 4, 0, 5],
       [0, 1, 0, 0, 2, 2, 0, 3, 0, 4, 0, 5],
       [0, 1, 0, 0, 2, 2, 0, 3, 0, 4, 0, 5],
       [0, 1, 0, 0, 2, 2, 0, 3, 0, 4, 0, 5]], dtype=int32)

In [863]:
pred1[t_mask> 0]

array([0], dtype=int32)

In [864]:
true_masks


[None, array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=uint8), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)]

In [865]:
pred_masks

[None, array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8), array([[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0]], dtype=uint8), array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]], dtype=uint8), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=uint8), array([[0, 0, 0, 

In [866]:
t_mask = true_masks[1]
pred_true_overlap = pred1[t_mask > 0]
#pred_true_overlap_id = np.unique(pred_true_overlap)
  
#pred_true_overlap_id = list(pred_true_overlap_id)
#pred_true_overlap_id
pred_true_overlap

array([1, 1, 1, 1, 1], dtype=int32)

In [867]:
for true_new in true_id_list[1:]:

    t_mask = true_masks[true_new]
    pred_true_overlap = pred1[t_mask > 0]
    pred_true_overlap_id = np.unique(pred_true_overlap)
  
    pred_true_overlap_id = list(pred_true_overlap_id)
    for pred_new in pred_true_overlap_id:
        if pred_new == 0: # ignore
            continue # overlaping background
        
        p_mask = pred_masks[pred_new]
        total = (t_mask + p_mask).sum()
        inter = (t_mask * p_mask).sum()
        pairwise_inter[true_new-1, pred_new-1] = inter
        print(pairwise_inter)
        pairwise_union[true_new-1, pred_new-1] = total - inter

[[5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]
 [0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0.]]


In [868]:
pairwise_inter

array([[5., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 0., 0., 0., 4.],
       [0., 0., 0., 0., 0.]])

In [869]:
pairwise_union

array([[ 5.,  0.,  0.,  0.,  0.],
       [ 0., 14.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  4.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [870]:
pairwise_iou = pairwise_inter / (pairwise_union + 1.0e-6)

In [871]:
pairwise_iou

array([[0.9999998 , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.28571427, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.99999975],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [872]:
paired_pred= np.argmax(pairwise_iou, axis=1)
print('paired_pred',paired_pred)
pairwise_iou=np.max(pairwise_iou,axis=1)
pairwise_iou

paired_pred [0 1 4 0]


array([0.9999998 , 0.28571427, 0.99999975, 0.        ])

In [873]:
paired_true = np.nonzero(pairwise_iou > 0.0)[0]
paired_true

array([0, 1, 2])

In [874]:
paired_pred = paired_pred[paired_true]
paired_pred

array([0, 1, 4])

In [875]:
overall_inter = (pairwise_inter[paired_true, paired_pred]).sum()
overall_union = (pairwise_union[paired_true, paired_pred]).sum()

In [876]:
paired_true = (list(paired_true + 1))
paired_true

[1, 2, 3]

In [877]:
paired_pred = (list(paired_pred + 1))
paired_pred

[1, 2, 5]

In [878]:
true_id_list

[0, 1, 2, 3, 4]

In [879]:
pred_id_list

[0, 1, 2, 3, 4, 5]

In [880]:
unpaired_true = np.array([idx for idx in true_id_list[1:] if idx not in paired_true])
unpaired_pred = np.array([idx for idx in pred_id_list[1:] if idx not in paired_pred])
for true_id in unpaired_true:
    overall_union += true_masks[true_id].sum()
for pred_id in unpaired_pred:
    overall_union += pred_masks[pred_id].sum()
    #
aji_score = overall_inter / overall_union

In [881]:
aji_score

0.38235294117647056